name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:
    name: Flutter Job
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Specify a specific flutter version if needed
          # flutter-version: '2.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        env:
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.22.2-arm64
          PUB_CACHE: /Users/runner/.pub-cache

      - name: Analyze project source
        run: flutter analyze
        # optionally use --fatal-warnings to stop execution if any warnings are found

      - name: Run tests
        run: flutter test
