name: Flutter Test and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
      FLUTTER_ROOT: /opt/hostedtoolcache/flutter/3.22.2-stable/x64
      PUB_CACHE: /opt/hostedtoolcache/flutter/3.22.2-stable/x64/.pub-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Run analyze
        run: flutter analyze
      - name: Run test cases
        run: flutter test --no-pub

  build_appbundle:
    name: Flutter Release
    runs-on: macos-latest
    needs: [flutter_test]
    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
      FLUTTER_ROOT: /opt/hostedtoolcache/flutter/3.22.2-stable/x64
      PUB_CACHE: /opt/hostedtoolcache/flutter/3.22.2-stable/x64/.pub-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
      - name: Commit build artifacts
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "build_upload_notify"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/debug/*'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.MY_TOKEN }}
