name: Flutter Test and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_appbundle:
    name: Flutter Release
    runs-on: macos-latest
    needs: [flutter_test]
    env:
      JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/arm64
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
      FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/3.22.2-stable/arm64
      PUB_CACHE: /Users/runner/hostedtoolcache/flutter/3.22.2-stable/arm64/.pub-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
      - name: Configure Git
        run: |
          git config --global user.name 'subhasishpinku'
          git config --global user.email 'pinku.subhasish@gmail.com'
      - name: Pull latest changes
        run: git pull origin main
      - name: Push changes
        run: |
          git add .
          git commit -m "Build APK for release"
          git push https://subhasishpinku:${{ secrets.MY_TOKEN }}@github.com/subhasishpinku/flutter_CI_CD.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/debug/*'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.MY_TOKEN }}
